name: Create Backport PR
on:
  issue_comment:
    types: [created]
jobs:
  Backport:
    if: github.event.issue.pull_request && startswith(github.event.comment.body, '/backport')
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Create Backport PR
        uses: Scy-D2L/action-testing/backport@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}