on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Getting current lms release from Rally
    steps:
      - name: Get LMS Version Action Step
        id: getlmsver
        uses: Scy-D2L/action-testing/get-lms-release@main
      - name: Get the output
        run: echo "The version was ${{ steps.getlmsver.outputs.lms-version }}"
      # Use the output from the `get release` step to bump the current version
      - name: Match LMS Release Action Step
        id: matchlmsrelease
        uses: Scy-D2L/action-testing/match-lms-release@main
        with:
          lms-version: '${{ steps.getlmsver.outputs.lms-version }}'