name: Release
on:
  push:
    branches:
      - master
      - main
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
      - release/[0-9]+.[0-9]+.x

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Updating with current lms release from Rally
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Match LMS Release
        id: matchlmsrelease
        uses: Scy-D2L/action-testing/match-lms-release@main
        with:
          RALLY_API_KEY: ${{ secrets.RALLY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}