on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Getting current lms release from Rally
    steps:
      - name: Get LMS Version Action Step
        id: getlmsver
        uses: Scy-D2L/action-testing/match-lms@main
        with:
          who-to-greet: 'Nimbus the OctoDAD'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.getlmsver.outputs.lmsVersion }}"