on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Getting current lms release from Rally
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Get LMS Version
        id: getlmsver
        uses: Scy-D2L/action-testing/get-lms-release@main
      - name: Match LMS Release
        id: matchlmsrelease
        uses: Scy-D2L/action-testing/match-lms-release@main
        with:
          GITHUB_TOKEN: ${{ secrets.D2L_GITHUB_TOKEN }}
          lms-version: '${{ steps.getlmsver.outputs.lms-version }}'