on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: scy-d2l/action-testing/match-lms@v1.1
        with:
          who-to-greet: 'Nimbus the OctoDAD'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }} Object object"